services:
  neura_spark_listener:
    build:
      context: .
      dockerfile: dockerfile
    image: meetneuraai/neura-open-source-ui:latest
    container_name: ${CONTAINER_NAME}
    ports:
      - "4173:4173"  # Frontend client port
      - "4174:4174"  # Backend server port
    env_file:
      - .env
    environment:
      # SECURITY: Server-side API keys (not exposed to browser)
      - NODE_ENV=production
      - GROQ_API_KEY=${GROQ_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - NEURA_ROUTER_API_KEY=${NEURA_ROUTER_API_KEY}
      - FLOWISE_API_KEY=${FLOWISE_API_KEY}
      
      # Server-side API URLs
      - PORT=4174
      - VITE_PORT=${VITE_PORT}
      - GROQ_API_URL=${GROQ_API_URL}
      - OPENAI_API_URL=${OPENAI_API_URL}
      - CLAUDE_API_URL=${CLAUDE_API_URL}
      - GOOGLE_API_URL=${GOOGLE_API_URL}
      - OPENROUTER_API_URL=${OPENROUTER_API_URL}
      - NEURA_ROUTER_API_URL=${NEURA_ROUTER_API_URL}
      - FLOWISE_API_URL=${FLOWISE_API_URL}
      
      # Server-side provider configs
      - FLOWISE_CHATFLOW_ID=${FLOWISE_CHATFLOW_ID}
      - OPENROUTER_HTTP_REFERER=${OPENROUTER_HTTP_REFERER}
      - OPENROUTER_X_TITLE=${OPENROUTER_X_TITLE}
      - GOOGLE_API_MODEL=${GOOGLE_API_MODEL}
      - OPENAI_TTS_API_MODEL=${OPENAI_TTS_API_MODEL}
      - OPENAI_TTS_API_VOICE=${OPENAI_TTS_API_VOICE}
      - GROQ_STT_API_MODEL=${GROQ_STT_API_MODEL}
      
      # Client-side settings (safe to expose with VITE_ prefix)
      - VITE_BOXED_CHATBUBBLE_MODE_ENABLED=${VITE_BOXED_CHATBUBBLE_MODE_ENABLED}
      - DEFAULT_SYSTEM_PROMPT=${DEFAULT_SYSTEM_PROMPT}
      - DEFAULT_WELCOME_MESSAGE=${DEFAULT_WELCOME_MESSAGE}
      - VITE_BACKEND_SERVICE_PROVIDER=${VITE_BACKEND_SERVICE_PROVIDER}
      - VITE_GROQ_API_MODEL=${VITE_GROQ_API_MODEL}
      - VITE_STREAM_ENABLED=${VITE_STREAM_ENABLED}
      - VITE_REASONING_FORMAT=${VITE_REASONING_FORMAT}
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
      
      # Database
      - DATABASE_URL=${DATABASE_URL}
      
      # Azure Storage (SERVER-SIDE ONLY - SAS tokens are sensitive!)
      - AZURE_STORAGE_CONTAINER_ID=${AZURE_STORAGE_CONTAINER_ID}
      - AZURE_STORAGE_ACCOUNT_NAME=${AZURE_STORAGE_ACCOUNT_NAME}
      - AZURE_STORAGE_SAS_TOKEN=${AZURE_STORAGE_SAS_TOKEN}

    volumes:
      - ./public:/app/public
      - ./data/audio:/app/data/audio
      #- ./prisma:/app/prisma
      #- ./prisma/dev.db:/app/prisma/dev.db
      - ./prisma/db:/app/prisma/db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "7"
        compress: "true"
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: 2G
    restart: always